/**
 * @fileoverview The marker that makes an indicator discoverable, and the
 * metadata key behind it.
 *
 * Discovery matches this marker, never the shape of an object. A provider that
 * happens to expose a `name` and a `check` is not necessarily a readiness probe,
 * and scraping one into the readiness response would let an unrelated failure
 * take an application out of rotation. Marking is a declaration of intent, and
 * only a declaration counts.
 *
 * The key is a stable string literal rather than one generated by
 * `DiscoveryService.createDecorator()`. That helper mints a random key each time
 * the module holding it is loaded, and this package ships several bundles: a
 * sibling library decorating its indicator through the `./health` subpath would
 * get a different key than the scanner running from the package root, so nothing
 * would ever be discovered. A literal is identical in every copy.
 * @layer Contract
 */
import { SetMetadata } from '@nestjs/common'
import type { CustomDecorator } from '@nestjs/common'

/**
 * Reflect metadata key carrying the discoverable marker. Namespaced so it cannot
 * collide with a consumer's own metadata, and exported so a test — or a sibling
 * library's own conformance suite — can assert a class is marked without
 * depending on how the decorator is implemented.
 */
export const BYMAX_HEALTH_INDICATOR_METADATA = 'bymax-one:health-indicator'

/**
 * Mark a provider class as a readiness indicator, so `BymaxCoreModule` discovers
 * it without the application registering it by hand.
 *
 * The class must implement `IHealthIndicator`; a marked provider that does not
 * fails at bootstrap with a message naming it, rather than being skipped
 * silently. Discovery has to be enabled (`health.autoDiscover`) for the marker to
 * be read at all — marking a class in an application that never enables it costs
 * one metadata entry and changes nothing.
 *
 * @returns The class decorator carrying the marker.
 * @example
 *   \@BymaxHealthIndicator()
 *   \@Injectable()
 *   export class RedisHealthIndicator implements IHealthIndicator {
 *     readonly name = 'redis'
 *     async check(): Promise<HealthIndicatorResult> {
 *       return { status: 'up' }
 *     }
 *   }
 */
export function BymaxHealthIndicator(): CustomDecorator<string> {
  return SetMetadata(BYMAX_HEALTH_INDICATOR_METADATA, true)
}
